### ISSUE TITLE
Feedback for First Model/Views

### ISSUE THREAD

**Issue by kaseymccormick** [kaseymccormick/sinatra_project#18]
need Sumeet's approval
file structure https://github.com/kaseymccormick/sinatra_project

**Comment by sumeetjain** [comment]
- [x] If you're [finding by ID](https://github.com/kaseymccormick/sinatra_project/blob/master/database_class_methods.rb#L62-L75), you can only have one (or zero) objects being returned. So either return the object or `nil`. No need to return an Array at all, since that just "passes the buck" of figuring out if there's anything inside it. (This change should make your class's [find](https://github.com/kaseymccormick/sinatra_project/blob/master/models/responder.rb#L47-L54) method obsolete.)
- [x] [Indentation](https://github.com/kaseymccormick/sinatra_project/blob/master/controllers/responders.rb)
- [x] [Unnecessary parentheses](https://github.com/kaseymccormick/sinatra_project/blob/master/controllers/responders.rb#L21)
- [x] [Indentation](https://github.com/kaseymccormick/sinatra_project/blob/master/models/responder.rb)
- [x] [Redundant method](https://github.com/kaseymccormick/sinatra_project/blob/master/models/responder.rb#L61-L63) – might as well delete it and just use `all`.
- [x] [Confusing](https://github.com/kaseymccormick/sinatra_project/blob/master/models/responder.rb#L100-L102). Why is the method called `change_email` if it modifies `@title`?

**Comment by kaseymccormick** [comment]
Indentation errors are fixed
confusing @title was an error of copy pasting and not updating the attribute appropriately
parentheses are removed
redundant method removed

working on finding ID error

**Comment by kaseymccormick** [comment]
#notes on modifying find(id) to use for reference

``` ruby
  #Get a single row.
  #id - The record's Integer ID.
  #Returns an Array containing the Hash of the row.
  #find responder's email and age_id via id (MODULE)
  #
  # id - The Integer ID of the responder to return.
  #
  # Returns a responder object.
  def self.find_as_object(id)

    # using the `find` method from DatabaseClassMethods.
    result = Responder.find(id).first
    #responder.find(2) returns an array of objects from find(2) method all objects from id2's row
    #an array containing nothing or one object (only one object because id is primary key - there can only be one)
    #if nothing in array returns nil

    # if result is nil the initalize method expects a hash and therfore throws an error
    Responder.new(result)

  end  


```

**Comment by sumeetjain** [comment]
- [x] Now that you've [changed the method name](https://github.com/kaseymccormick/sinatra_project/blob/master/models/responder.rb#L75-L77), doesn't look a lot like what `attr_writer` and/or `attr_accessor` give you? When possible, please use Ruby's built-in functionality instead.
- [x] [Indentation](https://github.com/kaseymccormick/sinatra_project/tree/master/views/responders)

**Comment by kaseymccormick** [comment]
understanding reader and writer capabilities
reader

``` ruby
def age_id
  @age_id
end
```

writer

``` ruby
def age_id = (age_id)
  @age_id = age_id
end
```
